const debug = require('debug')('servera:routes_auth');
const express = require('express');
const router = express.Router();
const auth = require('../middleware/auth');

const db_Clients = require('../models/db_Clients');
const networkHelper = require('../helpers/networkHelper');

const pinHelper = require('../helpers/pinHelper');

/**
 * @api {post} /api/auth/connect 1. connect to server
 * @apiGroup B.auth
 * @apiPermission none (for making new connect) || connected users (for refreshing the connection)
 * @apiHeader {String} x-auth-token Connection PIN when making a new connection || The token got from /api/auth/connect when refreshing the connection.
 *
 * @apiDescription It will (make a new / refresh current) connection between the client and the server
 * @apiSuccess (Success) {Number} status 200
 * @apiSuccess (Success) {String} body The token
 * @apiSuccessExample {string} Success-Response:
 *          eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ2M2Q3MWVlOGU3Zjk2Y2ZlYTk4MTllOWI5ZGNiNWY0IiwiaXNBZG1pbiI6dHJ1ZSwiZXhwQ29kZSI6MTU2NzU5MjA2NDAwMCwiaWF0IjoxNTY3NTkyMDY0LCJleHAiOjE1Njc1OTI5NjR9.bqtY5HAA6CToZk6bVtIoGbZP880MdgtSZmksQ0QevZg
 */

router.post('/connect', (req, res) => {
    const ipAddr = networkHelper.getIpAddressFromReq(req);
    const client = db_Clients.getClient(ipAddr);

    if (client.getStatus() === 'disconnected') {
        makeNewConnection(req, res, client);
    } else {
        refreshConnection(req, res, client);
    }
})

function createNewSession(res, client) {
    client.createNewSession();
    const jwt = client.generateAuthToken();
    debug(jwt);
    res.status(200).send(jwt);
}

function refreshConnection(req, res, client) {
    auth(req, res, () => createNewSession(res, client));
}

function makeNewConnection(req, res, client) {
    const pin = req.header('x-auth-token');
    if (pin === pinHelper.getPin()) {
        createNewSession(res, client);
    } else {
        res.status(400).send('wrong pin');
    }
}

/**
 * @api {post} /api/auth/disconnect 2. disconnect from server
 * @apiGroup B.auth
 * @apiPermission connected users
 * @apiHeader {String} x-auth-token The token got from /api/auth/connect
 *
 * @apiDescription It will remove the connection between the client and the server
 * @apiSuccess (Success) {Number} status 200
 */
router.post('/disconnect', auth, (req, res) => {
    const ipAddr = networkHelper.getIpAddressFromReq(req);
    const client = db_Clients.getClient(ipAddr);
    client.cleanAllSessions();

    res.status(200).send();
})

/**
 * @api {put} /api/auth/put 3. set a new connection pin
 * @apiGroup B.auth
 * @apiPermission admin
 * @apiHeader {String} x-auth-token The token got from /api/auth/connect
 * 
 * @apiDescription It will change the connection pin of server. All tokens generated by the old pin will be invalid.
 * @apiParam {String} pin The connection pin
 * @apiParamExample {json} Request-Example:
 *          {
 *              "pin": "123456"
 *          }
 * @apiSuccess (Success) {Number} status 200
 */
router.put('/pin', auth, (req, res) => {

})

module.exports = router;